# Hypothesis Testing

The purpose of the test is to tell if there is any significant difference between two data sets.



## Overview

This module covers,

1) One sample and Two sample t-tests

2) ANOVA

3) Type I and Type II errors

4) Chi-Squared Tests

## Question 1 

*A student is trying to decide between two GPUs. He want to use the GPU for his research to run Deep learning algorithms, so the only thing he is concerned with is speed.*

*He picks a Deep Learning algorithm on a large data set and runs it on both GPUs 15 times, timing each run in hours. Results are given in the below lists GPU1 and GPU2.*

In [1]:
from   scipy             import stats 
import pandas            as pd
import numpy             as np
import matplotlib.pyplot as plt
import seaborn           as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
GPU1 = np.array([11,9,10,11,10,12,9,11,12,9,11,12,9,10,9])
GPU2 = np.array([11,13,10,13,12,9,11,12,12,11,12,12,10,11,13])

#Assumption: Both the datasets (GPU1 & GPU 2) are random, independent, parametric & normally distributed

Hint: You can import ttest function from scipy to perform t tests 

**First T test**

*One sample t-test*

Check if the mean of the GPU1 is equal to zero.
- Null Hypothesis is that mean is equal to zero.
- Alternate hypothesis is that it is not equal to zero.

In [3]:
from scipy.stats import ttest_1samp

GPU1_mean = np.mean(GPU1)
GPU2_mean = np.mean(GPU2)

print("GPU 1 mean:", GPU1_mean)
print("GPU 2 mean:", GPU2_mean)
print("\n")

h1 = ttest_1samp(GPU1, 0)
h2 = ttest_1samp(GPU2, 0)

print(h1)
print(h2)

GPU 1 mean: 10.333333333333334
GPU 2 mean: 11.466666666666667


Ttest_1sampResult(statistic=34.056241516158195, pvalue=7.228892044970457e-15)
Ttest_1sampResult(statistic=37.406459913272236, pvalue=1.969680571681882e-15)


- Rejecting null hypothesis (***mean is equal to zero***) and 
accept alternate hypothesis (***is not equal to zero***) as absolute T stat is more than 2 and p value is less than 0.05

- i.e. mean is not equal to zero.

## Question 2

Given,

Null Hypothesis : There is no significant difference between data sets

Alternate Hypothesis : There is a significant difference

*Do two-sample testing and check whether to reject Null Hypothesis or not.*

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [18]:
from scipy.stats import ttest_ind

ttest, pvalue = stats.ttest_ind(GPU1,GPU2)

print("ttest:", ttest, "pvalue:", pvalue)

if pvalue < 0.05:
  print("\n we reject null hypothesis as p-value: ", pvalue, "is lesser than common significance value of 0.05")
else:
  print("\n we failed to reject null hypothesis as p-value: ", pvalue, "is greater than common significance value of 0.05")

ttest: -2.627629513471839 pvalue: 0.013794282041452725

 we reject null hypothesis as p-value:  0.013794282041452725 is lesser than common significance value of 0.05


 This means both GPUs are not effectively the same speed.

## Question 3

He is trying a third GPU - GPU3.

In [6]:
GPU3 = np.array([9,10,9,11,10,13,12,9,12,12,13,12,13,10,11])

#Assumption: Both the datasets (GPU1 & GPU 3) are random, independent, parametric & normally distributed

*Do two-sample testing and check whether there is significant differene between speeds of two GPUs GPU1 and GPU3.*

#### Answer:

In [17]:
from scipy.stats import ttest_ind

ttest, pvalue = stats.ttest_ind(GPU1,GPU3)

print("ttest:", ttest, "pvalue:", pvalue)

if pvalue < 0.05:
  print("\n we reject null hypothesis as p-value: ", pvalue, "is lesser than common significance value of 0.05")
else:
  print("\n we failed to reject null hypothesis as p-value: ", pvalue, "is greater than common significance value of 0.05")

ttest: -1.4988943759093303 pvalue: 0.14509210993138993

 we failed to reject null hypothesis as p-value:  0.14509210993138993 is greater than common significance value of 0.05


This means both GPUs are effectively the same speed.

## ANOVA

## Question 4 

If you need to compare more than two data sets at a time, an ANOVA is your best bet. 

*The results from three experiments with overlapping 95% confidence intervals are given below, and we want to confirm that the results for all three experiments are not significantly different.*

But before conducting ANOVA, test equality of variances (using Levene's test) is satisfied or not. If not, then mention that we cannot depend on the result of ANOVA

In [8]:
import numpy as np

e1 = np.array([1.595440,1.419730,0.000000,0.000000])
e2 = np.array([1.433800,2.079700,0.892139,2.384740])
e3 = np.array([0.036930,0.938018,0.995956,1.006970])

#Assumption: All the 3 datasets (e1,e2 & e3) are random, independent, parametric & normally distributed

Perform levene test on the data

The Levene test tests the null hypothesis that all input samples are from populations with equal variances. Levene’s test is an alternative to Bartlett’s test bartlett in the case where there are significant deviations from normality.

source: scipy.org

#### Answer:

In [16]:
ttest, pvalue = stats.levene(e1,e2,e3)

print("ttest:", ttest, "pvalue:", pvalue)

if pvalue < 0.05:
  print("\n we reject null hypothesis as p-value: ", pvalue, "is lesser than common significance value of 0.05")
else:
  print("\n we failed to reject null hypothesis as p-value: ", pvalue, "is greater than common significance value of 0.05")


ttest: 2.6741725711150446 pvalue: 0.12259792666001798

 we failed to reject null hypothesis as p-value:  0.12259792666001798 is greater than common significance value of 0.05


Which means that the e1,e2 and e3 pass equality of variance test. So, we can perform ANOVA test.

## Question 5

The one-way ANOVA tests the null hypothesis that two or more groups have the same population mean. The test is applied to samples from two or more groups, possibly with differing sizes.

use stats.f_oneway() module to perform one-way ANOVA test

In [15]:
ttest, pvalue = stats.f_oneway(e1,e2,e3)

print("ttest:", ttest, "pvalue:", pvalue)

if pvalue < 0.05:
  print("\n we reject null hypothesis as p-value: ", pvalue, "is lesser than common significance value of 0.05")
else:
  print("\n we failed to reject null hypothesis as p-value: ", pvalue, "is greater than common significance value of 0.05")

ttest: 2.51357622845924 pvalue: 0.13574644501798466

 we failed to reject null hypothesis as p-value:  0.13574644501798466 is greater than common significance value of 0.05


That means e1,e2 and e3 are not significantly different.

## Question 6

*In one or two sentences explain about **TypeI** and **TypeII** errors.*

#### Answer:

- **Type I error** describes a situation where you reject the null hypothesis when it is actually true. This type of error is also known as a "false positive" or "false hit".

- **Type II error** describes a situation where you fail to reject the null hypothesis when it is actually false. Type II error is also known as a "false negative" or "miss".answer here

## Question 7 

You are a manager of a chinese restaurant. You want to determine whether the waiting time to place an order has changed in the past month from its previous population mean value of 4.5 minutes. 
State the null and alternative hypothesis.

#### Answer:


### The null hypothesis is that the population mean has not changed from its previous value of 4.5 minutes. 
This is stated as

H0: µ = 4.5

The alternative hypothesis is the opposite of the null hypothesis. Because the null hypothesis is that the population mean is 4.5 minutes, the alternative hypothesis is that the population mean is not 4.5 minutes. 

This is stated as

H1 : µ not equal to 4.5

## Chi square test

## Question 8

Let's create a small dataset for dice rolls of four players

In [19]:
import numpy as np
# Here d1 to d6 are the number of dice and four values in each dice represents value of dice for player 1 to player 4

d1 = [1, 6, 3, 4]
d2 = [2, 5, 1, 3]
d3 = [4, 2, 3, 1]
d4 = [3, 4, 1, 2]
d5 = [1, 6, 3, 5]
d6 = [3, 2, 2, 1]

dice = np.array([d1, d2, d3, d4, d5, d6])

run the test using SciPy Stats library

Depending on the test, we are generally looking for a threshold at either 0.05 or 0.01. Our test is significant (i.e. we reject the null hypothesis) if we get a p-value below our threshold.

For our purposes, we’ll use 0.01 as the threshold.

use stats.chi2_contingency() module 

This function computes the chi-square statistic and p-value for the hypothesis test of independence of the observed frequencies in the contingency table

Print the following:

- chi2 stat
- p-value
- degree of freedom
- contingency



In [20]:
from scipy import stats

chi2_stat, p_val, dof, ex = stats.chi2_contingency(dice)
print('Chi2_stat: {},\np-value: {},\nDegree of freedom: {},\nContingency: {}'.format(chi2_stat, p_val, dof, ex))

Chi2_stat: 11.445004959326388,
p-value: 0.720458335452983,
Degree of freedom: 15,
Contingency: [[2.88235294 5.14705882 2.67647059 3.29411765]
 [2.26470588 4.04411765 2.10294118 2.58823529]
 [2.05882353 3.67647059 1.91176471 2.35294118]
 [2.05882353 3.67647059 1.91176471 2.35294118]
 [3.08823529 5.51470588 2.86764706 3.52941176]
 [1.64705882 2.94117647 1.52941176 1.88235294]]


## Question 9

### Z-test

Get zscore on the above dice data using stats.zscore module from scipy. Convert zscore values to p-value and take mean of the array.

In [21]:
zscore = stats.zscore(dice)
p_values = stats.norm.sf(abs(zscore))
p_values.mean()

0.20239343794918715

## Question 10

A Paired sample t-test compares means from the same group at different times.

The basic two sample t-test is designed for testing differences between independent groups. 
In some cases, you might be interested in testing differences between samples of the same group at different points in time. 
We can conduct a paired t-test using the scipy function stats.ttest_rel(). 

In [22]:
before= stats.norm.rvs(scale=30, loc=100, size=500) ## Creates a normal distribution with a mean value of 100 and std of 30
after = before + stats.norm.rvs(scale=5, loc=-1.25, size=500)

Test whether a weight-loss drug works by checking the weights of the same group patients before and after treatment using above data.

In [23]:
stats.ttest_rel(a = before, b = after)

Ttest_relResult(statistic=5.53110209932074, pvalue=5.142424472191697e-08)